### ISSUE TITLE
Bug: schema not being shown 

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/explore.opensauced.pizza#28]
### Describe the bug

Schema is not parsed correctly in production

### Steps to reproduce

Open explore.opensauced.pizza
Note no schema shown
Find errors in console 

### Affected services

explore.opensauced.pizza

### Platforms

Desktop, Mobile

### Browsers

Chrome, Safari

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
think we need to update that script of yours to some of the latest OneGraph changes :<

**Comment by mtfoley** [comment]
Cool. I have a fix that I can push in a PR later today. That way the updates can have their own scope.
