### ISSUE TITLE
Feature: Filter `gong` and `outreach` subgraphs

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/explore.opensauced.pizza#32]
### Type of feature

📦 Chore

### Current behavior

OneGraph has been updated to have new subgraphs for `gong` and `outreach`.  Need to update our filtering to account for these.

### Suggested solution

Update regular expression as in prior updates (such as in #31)

### Additional context

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
good catch!
